[package]
name = "syntaxis-browser"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
dioxus = { version = "0.7.10" }
syntaxis-app-shell = { path = "../../crates/app-shell" }
syntaxis-runtime-browser = { path = "../../crates/runtime-browser" }

[features]
default = ["web"]
web = ["dioxus/web"]

[lints]
workspace = true
