// @generated by scripts/generate-pi-settings.mjs; do not edit.
// pi-settings-cache-digest: 74591ca7 07a62d82 832fc261 2f53111c 3b5d90b8 f8e38347 b7086e21 a22fdcff

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[allow(
    dead_code,
    reason = "schema variants depend on upstream settings metadata"
)]
pub enum PiSettingKind {
    Toggle,
    Select(&'static [&'static str]),
    Number,
    Text,
    StringArray,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PiSettingDefinition {
    pub section: &'static str,
    pub path: &'static str,
    pub label: &'static str,
    pub description: &'static str,
    pub kind: PiSettingKind,
    pub default_value: &'static str,
    pub setter: &'static str,
}

pub const PI_SETTING_DEFINITIONS: &[PiSettingDefinition] = &[
    PiSettingDefinition {
        section: "Model & thinking",
        path: "defaultProvider",
        label: "Default Provider",
        description: "Startup AI provider.",
        kind: PiSettingKind::Text,
        default_value: "Automatic",
        setter: "setDefaultProvider",
    },
    PiSettingDefinition {
        section: "Model & thinking",
        path: "defaultModel",
        label: "Default Model",
        description: "Startup model ID.",
        kind: PiSettingKind::Text,
        default_value: "Automatic",
        setter: "setDefaultModel",
    },
    PiSettingDefinition {
        section: "Model & thinking",
        path: "defaultThinkingLevel",
        label: "Default Thinking Level",
        description: "Startup thinking level.",
        kind: PiSettingKind::Select(&["off", "minimal", "low", "medium", "high", "xhigh", "max"]),
        default_value: "medium",
        setter: "setDefaultThinkingLevel",
    },
    PiSettingDefinition {
        section: "Conversation",
        path: "compaction.enabled",
        label: "Auto-compaction",
        description: "Enable automatic compaction.",
        kind: PiSettingKind::Toggle,
        default_value: "true",
        setter: "setCompactionEnabled",
    },
    PiSettingDefinition {
        section: "Reliability",
        path: "retry.enabled",
        label: "Automatic retries",
        description: "Enable automatic agent-level retry for transient failures.",
        kind: PiSettingKind::Toggle,
        default_value: "true",
        setter: "setRetryEnabled",
    },
    PiSettingDefinition {
        section: "Message delivery",
        path: "steeringMode",
        label: "Steering Mode",
        description: "How queued steering messages are delivered.",
        kind: PiSettingKind::Select(&["one-at-a-time", "all"]),
        default_value: "one-at-a-time",
        setter: "setSteeringMode",
    },
    PiSettingDefinition {
        section: "Message delivery",
        path: "followUpMode",
        label: "Follow Up Mode",
        description: "How queued follow-up messages are delivered.",
        kind: PiSettingKind::Select(&["one-at-a-time", "all"]),
        default_value: "one-at-a-time",
        setter: "setFollowUpMode",
    },
    PiSettingDefinition {
        section: "Images",
        path: "images.blockImages",
        label: "Block Images",
        description: "Prevent images from being sent to models.",
        kind: PiSettingKind::Toggle,
        default_value: "false",
        setter: "setBlockImages",
    },
    PiSettingDefinition {
        section: "Security & privacy",
        path: "defaultProjectTrust",
        label: "Default Project Trust",
        description: "Fallback project-trust behavior. **Can only be set in agent-directory settings.**",
        kind: PiSettingKind::Select(&["ask", "always", "never"]),
        default_value: "ask",
        setter: "setDefaultProjectTrust",
    },
    PiSettingDefinition {
        section: "Security & privacy",
        path: "enableInstallTelemetry",
        label: "Enable Install Telemetry",
        description: "Enable anonymous install/update reporting and selected provider attribution headers. Does not control update checks.",
        kind: PiSettingKind::Toggle,
        default_value: "true",
        setter: "setEnableInstallTelemetry",
    },
];
