// @generated by scripts/generate-pi-settings.mjs; do not edit.
// pi-settings-cache-key: ef599aab09d01ae76f122d038d61295f9d31f173c0178e11d007ea95f92a3163
// pi-coding-agent: 0.80.10

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PiSettingKind {
    Toggle,
    Select(&'static [&'static str]),
    Number,
    Text,
    StringArray,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PiSettingDefinition {
    pub section: &'static str,
    pub path: &'static str,
    pub label: &'static str,
    pub description: &'static str,
    pub kind: PiSettingKind,
    pub default_value: &'static str,
    pub setter: &'static str,
}

#[cfg_attr(not(feature = "server"), allow(dead_code))]
pub const PI_SETTINGS_SCHEMA_VERSION: &str = "0.80.10";

pub const PI_SETTING_DEFINITIONS: &[PiSettingDefinition] = &[
    PiSettingDefinition { section: "Model & thinking", path: "defaultProvider", label: "Default Provider", description: "Default provider (e.g., \"anthropic\", \"openai\")", kind: PiSettingKind::Text, default_value: "", setter: "setDefaultProvider" },
    PiSettingDefinition { section: "Model & thinking", path: "defaultModel", label: "Default Model", description: "Default model ID", kind: PiSettingKind::Text, default_value: "", setter: "setDefaultModel" },
    PiSettingDefinition { section: "Model & thinking", path: "defaultThinkingLevel", label: "Default Thinking Level", description: "\"off\", \"minimal\", \"low\", \"medium\", \"high\", \"xhigh\", \"max\"", kind: PiSettingKind::Select(&["off", "minimal", "low", "medium", "high", "xhigh", "max"]), default_value: "", setter: "setDefaultThinkingLevel" },
    PiSettingDefinition { section: "Conversation", path: "compaction.enabled", label: "Auto-compaction", description: "Enable auto-compaction", kind: PiSettingKind::Toggle, default_value: "true", setter: "setCompactionEnabled" },
    PiSettingDefinition { section: "Reliability", path: "retry.enabled", label: "Automatic retries", description: "Enable automatic agent-level retry on transient errors", kind: PiSettingKind::Toggle, default_value: "true", setter: "setRetryEnabled" },
    PiSettingDefinition { section: "Message delivery", path: "steeringMode", label: "Steering Mode", description: "How steering messages are sent: \"all\" or \"one-at-a-time\"", kind: PiSettingKind::Select(&["one-at-a-time", "all"]), default_value: "one-at-a-time", setter: "setSteeringMode" },
    PiSettingDefinition { section: "Message delivery", path: "followUpMode", label: "Follow Up Mode", description: "How follow-up messages are sent: \"all\" or \"one-at-a-time\"", kind: PiSettingKind::Select(&["one-at-a-time", "all"]), default_value: "one-at-a-time", setter: "setFollowUpMode" },
    PiSettingDefinition { section: "Images", path: "images.blockImages", label: "Block Images", description: "Block all images from being sent to LLM", kind: PiSettingKind::Toggle, default_value: "false", setter: "setBlockImages" },
    PiSettingDefinition { section: "Security & privacy", path: "defaultProjectTrust", label: "Default Project Trust", description: "Fallback project trust behavior: \"ask\", \"always\", or \"never\". Global setting only", kind: PiSettingKind::Select(&["ask", "always", "never"]), default_value: "ask", setter: "setDefaultProjectTrust" },
    PiSettingDefinition { section: "Security & privacy", path: "enableInstallTelemetry", label: "Enable Install Telemetry", description: "Send an anonymous install/update version ping after first install or changelog-detected updates. This does not control update checks", kind: PiSettingKind::Toggle, default_value: "true", setter: "setEnableInstallTelemetry" },
];
