// @generated by scripts/generate-pi-settings.mjs; do not edit.
// pi-settings-cache-key: 1369acc6eb728ac6426ee932dc9120a45cc2a044660671bd7db794306aaf1cb6
// pi-coding-agent: 0.80.10

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PiSettingKind {
    Toggle,
    Select(&'static [&'static str]),
    Number,
    Text,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PiSettingDefinition {
    pub section: &'static str,
    pub path: &'static str,
    pub label: &'static str,
    pub description: &'static str,
    pub kind: PiSettingKind,
    pub default_value: &'static str,
    pub setter: &'static str,
}

#[cfg_attr(not(feature = "server"), allow(dead_code))]
pub const PI_SETTINGS_SCHEMA_VERSION: &str = "0.80.10";

pub const PI_SETTING_DEFINITIONS: &[PiSettingDefinition] = &[
    PiSettingDefinition {
        section: "Defaults",
        path: "defaultProvider",
        label: "Default provider",
        description: "Provider used for new chats",
        kind: PiSettingKind::Text,
        default_value: "",
        setter: "setDefaultProvider",
    },
    PiSettingDefinition {
        section: "Defaults",
        path: "defaultModel",
        label: "Default model",
        description: "Model ID used for new chats",
        kind: PiSettingKind::Text,
        default_value: "",
        setter: "setDefaultModel",
    },
    PiSettingDefinition {
        section: "Defaults",
        path: "defaultThinkingLevel",
        label: "Thinking level",
        description: "Reasoning depth used for new chats",
        kind: PiSettingKind::Select(&["off", "minimal", "low", "medium", "high", "xhigh", "max"]),
        default_value: "medium",
        setter: "setDefaultThinkingLevel",
    },
    PiSettingDefinition {
        section: "Conversation",
        path: "compaction.enabled",
        label: "Auto-compact",
        description: "Compact context automatically when it grows too large",
        kind: PiSettingKind::Toggle,
        default_value: "true",
        setter: "setCompactionEnabled",
    },
    PiSettingDefinition {
        section: "Conversation",
        path: "retry.enabled",
        label: "Automatic retries",
        description: "Retry transient model-provider failures",
        kind: PiSettingKind::Toggle,
        default_value: "true",
        setter: "setRetryEnabled",
    },
    PiSettingDefinition {
        section: "Conversation",
        path: "steeringMode",
        label: "Steering mode",
        description: "How steering messages are delivered while Pi is working",
        kind: PiSettingKind::Select(&["one-at-a-time", "all"]),
        default_value: "one-at-a-time",
        setter: "setSteeringMode",
    },
    PiSettingDefinition {
        section: "Conversation",
        path: "followUpMode",
        label: "Follow-up mode",
        description: "How queued follow-up messages are delivered",
        kind: PiSettingKind::Select(&["one-at-a-time", "all"]),
        default_value: "one-at-a-time",
        setter: "setFollowUpMode",
    },
    PiSettingDefinition {
        section: "Network",
        path: "transport",
        label: "Transport",
        description: "Preferred transport for providers supporting multiple transports",
        kind: PiSettingKind::Select(&["auto", "sse", "websocket", "websocket-cached"]),
        default_value: "auto",
        setter: "setTransport",
    },
    PiSettingDefinition {
        section: "Network",
        path: "httpIdleTimeoutMs",
        label: "HTTP idle timeout",
        description:
            "Maximum idle gap while waiting for provider traffic, in milliseconds; zero disables it",
        kind: PiSettingKind::Number,
        default_value: "300000",
        setter: "setHttpIdleTimeoutMs",
    },
    PiSettingDefinition {
        section: "Resources",
        path: "enableSkillCommands",
        label: "Skill commands",
        description: "Register installed skills as /skill:name commands",
        kind: PiSettingKind::Toggle,
        default_value: "true",
        setter: "setEnableSkillCommands",
    },
    PiSettingDefinition {
        section: "Images",
        path: "images.autoResize",
        label: "Auto-resize images",
        description: "Resize large images for model compatibility",
        kind: PiSettingKind::Toggle,
        default_value: "true",
        setter: "setImageAutoResize",
    },
    PiSettingDefinition {
        section: "Images",
        path: "images.blockImages",
        label: "Block images",
        description: "Prevent images from being sent to model providers",
        kind: PiSettingKind::Toggle,
        default_value: "false",
        setter: "setBlockImages",
    },
    PiSettingDefinition {
        section: "Privacy",
        path: "enableInstallTelemetry",
        label: "Install telemetry",
        description: "Send Pi's anonymous version/update ping",
        kind: PiSettingKind::Toggle,
        default_value: "true",
        setter: "setEnableInstallTelemetry",
    },
    PiSettingDefinition {
        section: "Startup",
        path: "quietStartup",
        label: "Quiet startup",
        description: "Reduce Pi startup output",
        kind: PiSettingKind::Toggle,
        default_value: "false",
        setter: "setQuietStartup",
    },
];
